# Generated by Django 6.0.7 on 2026-08-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executejob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Execute Job', 'verbose_name_plural': 'Execute Jobs'},
        ),
        migrations.AlterModelOptions(
            name='executelog',
            options={'ordering': ['created_at'], 'verbose_name': 'Execute Log', 'verbose_name_plural': 'Execute Logs'},
        ),
        migrations.AlterField(
            model_name='executelog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20),
        ),
    ]
