# Generated by Django 6.0.7 on 2026-08-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_alter_executejob_options_alter_executelog_options_and_more'),
        ('testcase', '0001_initial'),
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executejob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='executelog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='executejob',
            name='testplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execute_jobs', to='testplan.testplan'),
        ),
        migrations.AlterField(
            model_name='executelog',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execute_logs', to='testcase.testcase'),
        ),
    ]
