# Generated by Django 6.0.7 on 2026-08-11 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_alter_executejob_options_alter_executelog_options_and_more'),
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executejob',
            name='current_test_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executejob',
            name='current_testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_execute_jobs', to='testcase.testcase'),
        ),
    ]
